doocs/qcloud-im-server-sdk-java

src/main/java/io/github/doocs/im/model/response/GetNoSpeakingResult.java

fix: add noSpeaking result fields

---

README.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/ClientConfiguration.java
src/main/java/io/github/doocs/im/ImClient.java
src/main/resources/version.properties

for more details, refer to #63

feat: auto renew user sig

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

- Support custom domain in ImClient #76 
- Upgrade Okhttp version to v4.9.3

build: release v0.3.1

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/model/callback/AfterSendGroupMsgCallback.java
src/main/java/io/github/doocs/im/model/callback/BeforeSendGroupMsgCallback.java
src/main/java/io/github/doocs/im/model/callback/BeforeSendGroupMsgResponse.java
src/main/resources/version.properties

feat: add CloudCustomData field in callback entities

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/model/group/GroupInfo.java
src/main/resources/version.properties

fix: group info entity

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.16

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/message.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/core/Message.java
src/main/java/io/github/doocs/im/model/request/ModifyC2cMsgRequest.java
src/main/java/io/github/doocs/im/model/response/ModifyC2cMsgResult.java
src/main/resources/version.properties
src/test/java/io/github/doocs/im/MessageTest.java

build: release v0.3.17

---

docs/guide/operation_2.md
src/main/java/io/github/doocs/im/constant/ResourceStatus.java
src/main/java/io/github/doocs/im/core/Operation.java
src/main/java/io/github/doocs/im/model/request/AllowBannedObjectRequest.java
src/main/java/io/github/doocs/im/model/request/ForbidIllegalObjectRequest.java
src/main/java/io/github/doocs/im/model/request/GetCosSigRequest.java
src/main/java/io/github/doocs/im/model/request/RawUrlItem.java
src/main/java/io/github/doocs/im/model/response/AllowBannedObjectResult.java
src/main/java/io/github/doocs/im/model/response/ForbidIllegalObjectResult.java
src/main/java/io/github/doocs/im/model/response/GetCosSigResult.java
src/main/java/io/github/doocs/im/model/response/PreSigUrlItem.java
src/test/java/io/github/doocs/im/OperationTest.java

新增运营管理 API
* 聊天文件封禁
* 聊天文件解封
* 聊天文件签名

feat: new operation api

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/constant/NetType.java
src/main/resources/version.properties

* 服务器 IP 地址列表指定类型
* 新增运营管理 API(聊天文件封禁、解封、签名)

buiid: release v0.3.18

---

README.md
README_CN.md
docs/.vuepress/config.js
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

* node & 依赖包 版本升级
* IM 客户端部分优化

build: release v0.3.20

---

src/main/java/io/github/doocs/im/model/callback/AfterCreateGroupCallback.java
src/main/java/io/github/doocs/im/model/callback/AfterMemberExitCallback.java
src/main/java/io/github/doocs/im/model/callback/AfterNewMemberJoinCallback.java
src/main/java/io/github/doocs/im/model/callback/BeforeCreateGroupCallback.java
src/main/java/io/github/doocs/im/model/callback/BeforeInviteJoinGroupCallback.java
src/main/java/io/github/doocs/im/model/callback/MemberAccount.java
src/main/java/io/github/doocs/im/model/callback/OnMemberStateChangeCallback.java

feat: add new callback entity

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

* 升级 JUnit 框架
* 新增 Callback 回调类

build: release v0.3.21

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/group.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/core/Group.java
src/main/java/io/github/doocs/im/model/request/GetMembersRequest.java
src/main/java/io/github/doocs/im/model/response/GetMembersResult.java
src/main/java/io/github/doocs/im/model/response/MemberListItem.java
src/main/resources/version.properties
src/test/java/io/github/doocs/im/core/GroupTest.java

* 添加新 API : 获取直播群在线列表
* 发布 v0.3.22

build: release v0.3.22

---

src/main/java/io/github/doocs/im/ClientConfiguration.java
src/main/java/io/github/doocs/im/ImClient.java
src/main/java/io/github/doocs/im/util/HttpUtil.java

项目中原来使用的为默认okhttp连接池，连接池的最大连接数为5，在某些场景下容易达到性能瓶颈

添加okhttp连接池配置

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.23

---

docs/guide/group.md
src/main/java/io/github/doocs/im/core/Group.java
src/main/java/io/github/doocs/im/model/request/ModifyGroupMsgRequest.java
src/main/java/io/github/doocs/im/model/request/SendBroadcastMsgRequest.java
src/main/java/io/github/doocs/im/model/response/ModifyGroupMsgResult.java
src/main/java/io/github/doocs/im/model/response/SendBroadcastMsgResult.java
src/test/java/io/github/doocs/im/core/GroupTest.java

feat: add new group api

---

docs/guide/group.md
pom.xml
src/main/java/io/github/doocs/im/constant/MuteAllMember.java
src/main/java/io/github/doocs/im/core/Group.java
src/main/java/io/github/doocs/im/model/group/GroupInfo.java
src/main/java/io/github/doocs/im/model/group/MemberProfile.java
src/main/java/io/github/doocs/im/model/request/ForbidSendMsgRequest.java
src/main/java/io/github/doocs/im/model/request/GetGroupMsgReceiptDetailRequest.java
src/main/java/io/github/doocs/im/model/request/GetGroupMsgReceiptRequest.java
src/main/java/io/github/doocs/im/model/request/GetGroupMutedAccountRequest.java
src/main/java/io/github/doocs/im/model/request/ModifyGroupBaseInfoRequest.java
src/main/java/io/github/doocs/im/model/request/ModifyGroupMemberInfoRequest.java
src/main/java/io/github/doocs/im/model/response/GetGroupMsgReceiptDetailResult.java
src/main/java/io/github/doocs/im/model/response/GetGroupMsgReceiptResult.java
src/main/java/io/github/doocs/im/model/response/GetGroupMutedAccountResult.java
src/main/java/io/github/doocs/im/model/response/GroupMsgReceiptResultItem.java
src/main/java/io/github/doocs/im/model/response/MutedAccountItem.java
src/main/java/io/github/doocs/im/model/response/ReadAccountItem.java
src/main/java/io/github/doocs/im/model/response/UnreadAccountItem.java
src/test/java/io/github/doocs/im/core/GroupTest.java

* 添加 拉取群消息已读回执信息,拉取群消息已读回执详情 api
* 将 shutup 字段重命名为 muted

feat: add new group api and modify group fields

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

* 添加群组新 api
* 部分字段修改 shutup -> mute

build: relase v0.3.24

---

docs/guide/quickstart.md
src/main/java/io/github/doocs/im/ClientConfiguration.java
src/main/java/io/github/doocs/im/util/HttpUtil.java
src/test/java/io/github/doocs/im/ClientFactory.java

* 修改默认超时时间
* 新增 call timeout 自定义参数

feat: default timeout setting

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

* 修改默认超时时间
* 新增 call timeout 自定义参数

build: release v0.3.25

---

src/main/java/io/github/doocs/im/model/group/GroupInfo.java
src/main/java/io/github/doocs/im/model/request/GetAppIdGroupListRequest.java
src/main/java/io/github/doocs/im/model/request/GroupMsgGetSimpleRequest.java
src/main/java/io/github/doocs/im/model/response/GetAppIdGroupListResult.java
src/test/java/io/github/doocs/im/core/GroupTest.java

* GroupInfo: infoSeq, nextMsgSeq
* GroupMsgGetSimpleRequest: reqMsgSeq
* GetAppIdGroupListRequest: next
* GetAppIdGroupListResult: next

fix: integer -> long

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.26

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.27

---

docs/guide/group.md
pom.xml
src/main/java/io/github/doocs/im/core/Group.java
src/main/java/io/github/doocs/im/model/callback/AfterCreateGroupTopicCallback.java
src/main/java/io/github/doocs/im/model/callback/AfterDestroyGroupTopicCallback.java
src/main/java/io/github/doocs/im/model/callback/AfterModifyGroupTopicCallback.java
src/main/java/io/github/doocs/im/model/callback/BeforeCreateGroupTopicCallback.java
src/main/java/io/github/doocs/im/model/callback/UserDefinedDataItem.java
src/main/java/io/github/doocs/im/model/request/CreateGroupTopicRequest.java
src/main/java/io/github/doocs/im/model/request/DestroyGroupTopicRequest.java
src/main/java/io/github/doocs/im/model/request/GetGroupTopicRequest.java
src/main/java/io/github/doocs/im/model/request/ModifyGroupTopicRequest.java
src/main/java/io/github/doocs/im/model/request/TopicDefinedDataItem.java
src/main/java/io/github/doocs/im/model/response/CreateGroupTopicResult.java
src/main/java/io/github/doocs/im/model/response/DestroyGroupTopicResult.java
src/main/java/io/github/doocs/im/model/response/DestroyGroupTopicResultItem.java
src/main/java/io/github/doocs/im/model/response/GetGroupTopicResult.java
src/main/java/io/github/doocs/im/model/response/GroupIdListResultItem.java
src/main/java/io/github/doocs/im/model/response/ModifyGroupTopicResult.java
src/main/java/io/github/doocs/im/model/response/SelfInfo.java
src/main/java/io/github/doocs/im/model/response/TopicAndSelfInfoItem.java
src/main/java/io/github/doocs/im/model/response/TopicInfo.java
src/test/java/io/github/doocs/im/core/GroupTest.java

feat: add group topic api

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.28

---

src/main/java/io/github/doocs/im/model/group/MemberProfile.java
src/main/java/io/github/doocs/im/model/response/MutedAccountItem.java

fix: muteUntil type

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.30

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.31

---

docs/guide/group.md
docs/guide/message.md
src/main/java/io/github/doocs/im/constant/OperateType.java
src/main/java/io/github/doocs/im/constant/SupportMessageExtension.java
src/main/java/io/github/doocs/im/core/Group.java
src/main/java/io/github/doocs/im/core/Message.java
src/main/java/io/github/doocs/im/model/request/GetKeyValuesRequest.java
src/main/java/io/github/doocs/im/model/request/GroupGetKeyValuesRequest.java
src/main/java/io/github/doocs/im/model/request/GroupSetKeyValuesRequest.java
src/main/java/io/github/doocs/im/model/request/ProfileItem.java
src/main/java/io/github/doocs/im/model/request/SendGroupMsgRequest.java
src/main/java/io/github/doocs/im/model/request/SendMsgRequest.java
src/main/java/io/github/doocs/im/model/request/SetKeyValuesRequest.java
src/main/java/io/github/doocs/im/model/response/ExtensionMsg.java
src/main/java/io/github/doocs/im/model/response/GetKeyValuesResult.java
src/main/java/io/github/doocs/im/model/response/GroupGetKeyValuesResult.java
src/main/java/io/github/doocs/im/model/response/GroupSetKeyValuesResult.java
src/main/java/io/github/doocs/im/model/response/KeyValueSeq.java
src/main/java/io/github/doocs/im/model/response/SetKeyValuesResult.java
src/test/java/io/github/doocs/im/core/GroupTest.java
src/test/java/io/github/doocs/im/core/MessageTest.java

feat: add new group and message api

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.32

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/model/callback/AfterSendGroupMsgCallback.java
src/main/resources/version.properties

build: release v0.3.33

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.35

---

docs/guide/group.md
src/main/java/io/github/doocs/im/constant/GroupCounterMode.java
src/main/java/io/github/doocs/im/core/Group.java
src/main/java/io/github/doocs/im/model/group/GroupCounterItem.java
src/main/java/io/github/doocs/im/model/request/DeleteGroupCounterRequest.java
src/main/java/io/github/doocs/im/model/request/GetGroupCounterRequest.java
src/main/java/io/github/doocs/im/model/request/UpdateGroupCounterRequest.java
src/main/java/io/github/doocs/im/model/response/DeleteGroupCounterResult.java
src/main/java/io/github/doocs/im/model/response/GetGroupCounterResult.java
src/main/java/io/github/doocs/im/model/response/UpdateGroupCounterResult.java
src/test/java/io/github/doocs/im/core/GroupTest.java

feat: implement group counter api

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.37

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/resources/version.properties

build: release v0.3.45

---

docs/guide/group.md
src/main/java/io/github/doocs/im/constant/InviteJoinOption.java
src/main/java/io/github/doocs/im/model/group/GroupInfo.java
src/main/java/io/github/doocs/im/model/request/CreateGroupRequest.java

Add missing property InviteJoinOption for GroupInfo and CreateGroupRequest.
See also [/document/product/269/1615](https://cloud.tencent.com/document/product/269/1615)

chore: group InviteJoinOption

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/model/callback/AfterSendGroupMsgCallback.java
src/main/resources/version.properties

feat: add field groupAtInfo in AfterSendGroupMsgCallback

feat: add field groupAtInfo in AfterSendGroupMsgCallback

---

src/main/java/io/github/doocs/im/model/callback/AfterSendGroupMsgCallback.java

feat: modify GroupAtInfoItem private to public

feat: modify GroupAtInfoItem private to public

---

README.md
README_CN.md
docs/guide/README.md
docs/guide/quickstart.md
package-lock.json
package.json
pom.xml
src/main/java/io/github/doocs/im/model/response/RspMsgItem.java
src/main/resources/version.properties

fix: msgbody type

---

src/main/java/io/github/doocs/im/ClientConfiguration.java
src/main/java/io/github/doocs/im/util/HttpUtil.java

The HTTP request retry class has added a feature that allows for retries based on business error codes

feat: Should retry based on business code

---

src/main/java/io/github/doocs/im/util/HttpUtil.java

Update HttpUtil.java fix business code retry

---

src/main/java/io/github/doocs/im/core/Account.java
src/main/java/io/github/doocs/im/model/request/MultiAccountImportNewRequest.java
src/test/java/io/github/doocs/im/core/AccountTest.java

https://cloud.tencent.com/document/product/269/4919
支持新版本请求参数：
{
"AccountList": [
{
"UserID": "UserID_001",
"Nick": "Nick_001",
"FaceUrl": "http://www.qq.com"
},
{
"UserID": "UserID_002",
"Nick": "Nick_002",
"FaceUrl": "http://www.qq.com"
},
{
"UserID": "UserID_002",
"Nick": "Nick_001",
"FaceUrl": "http://www.qq.com"
}
]
}

feat:导入多账号支持新版本参数：昵称和头像
